### ISSUE TITLE
Redirecting Customer to Portal

### ISSUE THREAD

**Issue by dmpgordon** [mailru/jira-plugins-jsincluder#6]
Hi there,
We are all using your mailru calendar - fantastic work!!!

This issue is we have added the mailru calendar to a menu for the portal user but when you select an issue this is redirecting the user to the jira (.../browse/...) instead of the portal site ( .../servicedesk/customer/portal/?/...) 

I have installed your JSIncluder and added a script that is linked to a View binding;

The redirections works well apart from the fact that the user initially sees the Jira Issue page before being redirected to the portal.  Is there any way to avoid the JIRA issue page being displayed?  

Kind regards
Dave

**Comment by dariarostshina** [comment]
Hi, Dave!

JSIncluder Scripts work after the page has been fully loaded, since you usually need to do something with its contents.
To solve your problem, you need to configure the configuration of your web server or write a plugin for JIRA, implementing a [servlet-filter](https://developer.atlassian.com/jiradev/jira-platform/building-jira-add-ons/jira-plugins2-overview/jira-plugin-module-types/servlet-filter-plugin-module).

Kind regards
Daria
